<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This field is required_status</name>
   <tag></tag>
   <elementGuidId>2beaed45-892c-4f8e-9e15-4e064249745d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ea28199-4150-41ad-8350-f381fb606a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b134d381-02f4-4a59-a5b2-237edac29519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>9cf9327e-a517-42b4-ba45-94c05aba6534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idle</value>
      <webElementGuid>8f00999f-2a31-496e-a60d-5704e67e184d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>bf962ddc-4b7e-4207-8a8c-0ea282f5b4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Idle</value>
      <webElementGuid>4e39c0c4-7c12-4eb8-8190-b5bda40f181c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idle&quot;)</value>
      <webElementGuid>ee248fe4-e023-49ba-9932-059f096b3e3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idle']</value>
      <webElementGuid>731bce11-88b6-4a2c-abaa-ee4e12d461a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPlacement']/div/div/div[2]/form/div[6]/div/div[2]/input</value>
      <webElementGuid>82c68188-9ffb-42d0-876b-178b68650cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>5e5d88ee-7a62-47c5-9aaf-9ee0e20af301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'idle' and @name = 'status']</value>
      <webElementGuid>cf0b3e1c-2291-4ea5-ad19-ebbae3f4d212</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
