<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Role_jobRole</name>
   <tag></tag>
   <elementGuidId>8c49f4f2-034f-46e9-88ff-7dde6e1d8768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobRole</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobRole']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30f43221-66fb-4379-8789-493529fad073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98591418-4d80-4c64-bf15-da51d7799794</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>294f1c16-7bb2-4646-8c51-5c5378dd34a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobRole</value>
      <webElementGuid>972d3b1c-c054-40f0-9a26-4821ad3e47b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobRole</value>
      <webElementGuid>28ad361e-d11d-4a5f-a231-1bd15a678e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobRole&quot;)</value>
      <webElementGuid>eb769fff-8ea0-4e07-8977-3fed78db8825</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobRole']</value>
      <webElementGuid>0c7b3b06-9bbb-4363-ae27-01aeb057f71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPlacement']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>24a7f9d5-d127-43af-a899-4f74956a9422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>74607a1f-30f7-473a-9534-d0fb288e2817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'jobRole' and @name = 'jobRole']</value>
      <webElementGuid>611daebd-769e-4e38-989e-7d054cb0c7b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
