<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Role_EndContract</name>
   <tag></tag>
   <elementGuidId>8fb4fa41-3ede-426a-bf38-2bf26f0f8a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EndContract</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EndContract']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d3c6b40-1d31-4d81-98bd-dd1ea6323279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>31d6a4ea-3106-4a4f-908f-ccd2cc320b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>2aece4ee-d9fe-46f6-ae19-5738e992b04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EndContract</value>
      <webElementGuid>989679ac-143a-4d21-80e1-f7a843f97a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EndContract</value>
      <webElementGuid>34f4d1bd-cf46-496d-a4cd-970ea5edd0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EndContract&quot;)</value>
      <webElementGuid>69c386bb-f626-4aa9-9653-65654b9a563b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EndContract']</value>
      <webElementGuid>1feb962a-cc74-4298-ae33-d07197e7c9e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalContract']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>93792049-16d6-44c4-966d-f9809d447faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>65256784-489b-42ff-a9c5-b058e6d08165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'EndContract' and @name = 'EndContract']</value>
      <webElementGuid>56f3e288-4ad9-4753-b878-dbbf94e0bb25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
