<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Contract_StartContract</name>
   <tag></tag>
   <elementGuidId>57dcc08f-b06a-4896-b3d9-e6bf41243006</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#StartContract</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='StartContract']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e2e1d3a-6ae3-438e-9c72-2c60a55ad3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>bd0f39d6-17fc-4e2a-a29f-a80fd4d7a0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>c7e9f8a6-c67e-4c83-893d-d7c934cde44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StartContract</value>
      <webElementGuid>607b7d79-dc4e-4400-81cf-ab48df04696b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StartContract</value>
      <webElementGuid>45166229-25db-4111-8e15-a6ee75b806b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StartContract&quot;)</value>
      <webElementGuid>ee3b5957-4b3a-4250-886e-1339d404f847</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='StartContract']</value>
      <webElementGuid>f2b7c663-923e-4ec1-864e-faacde09be19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalContract']/div/div/div[2]/form/div/input</value>
      <webElementGuid>2eab1ae7-20d6-4cd1-8b32-55ea80e63e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>06cfb45f-2575-48f0-935b-099f2d007484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'StartContract' and @name = 'StartContract']</value>
      <webElementGuid>f7e1a9f4-bc53-40b0-a01d-acff096a68da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
