<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_hiredStatus</name>
   <tag></tag>
   <elementGuidId>f8b5c606-0f5c-4a71-bca7-403492710617</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bootcamp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bootcamp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2f9c963-56fa-47f5-8d3c-5671b49d81c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>209d21ce-d81d-441d-9bc4-312287dd9703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a0f53518-4b8a-4875-b3aa-0b0c49a06710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bootcamp</value>
      <webElementGuid>03f3c5d4-d553-48d6-9a4c-7d93a27adc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hiredStatus</value>
      <webElementGuid>d6a8e422-81f4-430d-a2c6-cb64897c1e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Bootcamp</value>
      <webElementGuid>4497c761-adf8-4764-87da-a908b4bcd56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bootcamp&quot;)</value>
      <webElementGuid>fd6672c0-cb04-4653-87bc-8ecb38d9d3fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bootcamp']</value>
      <webElementGuid>8cffd0c6-c57a-4a8e-aa6d-e4fe6f01a1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formHiring']/div/div[2]/input</value>
      <webElementGuid>1308c527-9c9e-4dbc-9580-4f8db1bfa81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>dfa8316b-5331-4327-9042-76c6b3e524d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'bootcamp' and @name = 'hiredStatus']</value>
      <webElementGuid>f1dba9c7-2f62-4b15-8ea5-8eb8154027a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
