<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This field is required_repeatPassword</name>
   <tag></tag>
   <elementGuidId>4a6baac0-d341-462e-a44f-1a14ad6ad21c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#repeatPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repeatPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f23fca9e-1894-491f-a995-86ddd58e1f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5eece48e-cfe2-4da8-b374-132109d93542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-user</value>
      <webElementGuid>44843a89-4b3e-48cd-8c56-bf170fe3d202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repeatPassword</value>
      <webElementGuid>dafc8b84-ebc6-4633-ab69-21bdbb7ff28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeatPassword</value>
      <webElementGuid>686afb3f-7d29-4ec5-9169-8ecac255915f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Repeate Password</value>
      <webElementGuid>1a4adecd-fcce-4aeb-8b70-fcd6fc5fb253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeatPassword&quot;)</value>
      <webElementGuid>31d43261-57b3-4854-a3f1-c905c9a58e39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repeatPassword']</value>
      <webElementGuid>234edbc6-c5db-4063-93c2-ed9751316dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='resetPassword']/div[3]/input</value>
      <webElementGuid>7db087bd-1bf6-49c4-b3cc-d6c9f6429262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>136890d4-e05c-4518-bbbf-2e2ba3edfe91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'repeatPassword' and @name = 'repeatPassword' and @placeholder = 'Repeate Password']</value>
      <webElementGuid>22f9a168-6a65-497d-a5cc-bd1e882669c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
