<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Change Password_currentPassword</name>
   <tag></tag>
   <elementGuidId>ed20da8e-92f1-48a9-8788-ab52d257c582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currentPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='currentPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec84d2b0-8af9-4af0-9f68-9532feb66518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a08a2d52-42e5-4d33-8441-ef7c4eb1c166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-user</value>
      <webElementGuid>02ef4f46-fa2c-4f23-b4da-d5b2289fb6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currentPassword</value>
      <webElementGuid>8350da8c-0168-433f-915f-7be409342547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Current Password</value>
      <webElementGuid>1c3acd7d-0855-478b-b0c5-8a13af3e8aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currentPassword&quot;)</value>
      <webElementGuid>0d201247-97d7-48b4-b824-a6fa43540dfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='currentPassword']</value>
      <webElementGuid>6828e413-8ae4-419a-ba8c-fb612b207c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='resetPassword']/div/input</value>
      <webElementGuid>51436b6e-a488-4957-a927-dc7bd96b1d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4024b995-78b7-4310-9104-95b4658f68da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'currentPassword' and @placeholder = 'Current Password']</value>
      <webElementGuid>ac72f901-8ad2-405d-a0f5-c2987cd31c5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
