<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This field is required_newPassword</name>
   <tag></tag>
   <elementGuidId>5f0a6a6a-9f32-48f2-adcc-2a8a9475161a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09db25e1-1376-4989-8033-3c8db8c6f101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>0dfb7261-b72d-4b80-a347-302a0f3ecbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-user</value>
      <webElementGuid>aecd5480-4129-49ec-8783-0d28e607bf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newPassword</value>
      <webElementGuid>0d271301-1d1a-4fac-82ec-d6f36cf3b1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newPassword</value>
      <webElementGuid>8831fe1e-be64-407e-b220-2a57a6c4b978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New Password</value>
      <webElementGuid>e418930d-f062-4aeb-9b9e-e88645ff2d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newPassword&quot;)</value>
      <webElementGuid>9f1ac9c7-2620-466f-af75-e92784b0c379</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newPassword']</value>
      <webElementGuid>d6e4ba88-8ada-4e46-9b62-1e79e20cf041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='resetPassword']/div[2]/input</value>
      <webElementGuid>1bbefaa1-a83a-464b-af82-e3ed6cfe4942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>22aaa510-11e9-441a-80a6-8dfbe6ba4ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'newPassword' and @name = 'newPassword' and @placeholder = 'New Password']</value>
      <webElementGuid>97abbf9d-544b-4b2a-b66e-5f7a584a558e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
