<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>0ad57aad-fcd0-4cc7-8a62-e96249ed5ca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Update</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='Update']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b437383e-fb06-4f08-9c53-9d77355b9540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>914a35c1-ffa1-47c2-b8a9-c866b1a937ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>d69b2f1d-0e4d-4d75-b8d8-621f96821559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>d6e3aaad-98e1-44f0-86b0-b3ef679438a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SaveTurnOver();</value>
      <webElementGuid>affe6889-0e24-4ae8-9853-eb4ce3696c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update</value>
      <webElementGuid>98b62f05-a90b-44b3-9a29-2bf722f1d9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Update&quot;)</value>
      <webElementGuid>187797de-a347-46e3-99d7-b755cf125eff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='Update']</value>
      <webElementGuid>ffdee4ab-5426-4f44-b3bc-a8877501ae16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Modal']/div/div/div[3]/button</value>
      <webElementGuid>8e093dd6-14e4-416f-aa22-14372b6ae6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>4b3b9565-b452-4409-860c-e8b6308011e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'Update' and (text() = 'Update' or . = 'Update')]</value>
      <webElementGuid>fd66d5f5-20c4-42b4-b224-8b292fbc6c2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
