<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TurnOver</name>
   <tag></tag>
   <elementGuidId>ad4f47f1-b2d8-4898-9460-9de2e14157f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.even > td:nth-of-type(6) > button.badge.badge-pill.badge-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;return GetByIdPlacement('RAS17072023008', 'Onsite')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd5d77b7-b113-47dc-9bac-a47666ba7c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge badge-pill badge-success</value>
      <webElementGuid>377ac073-d5a4-4e46-9149-9552c62a6c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>0077f9f3-8103-49c6-8e40-b85e7c893ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>02f1f323-32f2-4e84-b1de-33df30100047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>animation</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>386e8b0c-b991-4d66-9800-daa3e4683d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>27567c1b-1c75-425e-aaf8-9c381f36d415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return GetByIdPlacement('RAS17072023008', 'Onsite')</value>
      <webElementGuid>378da6b6-3b3a-486c-b5a1-5d0c4a2799eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Onsite</value>
      <webElementGuid>5162c034-2f60-45ce-823f-aad28503c18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataTableEmployee&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[6]/button[@class=&quot;badge badge-pill badge-success&quot;]</value>
      <webElementGuid>c5110995-b0c6-4191-ae44-a04f9af2d398</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;return GetByIdPlacement('RAS17072023008', 'Onsite')&quot;]</value>
      <webElementGuid>56d3ac1a-1602-46c8-aa71-f20ae4b5378d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dataTableEmployee']/tbody/tr[4]/td[6]/button</value>
      <webElementGuid>aaf75ff6-9964-4028-bc8e-9daa09cfc277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[6]/button</value>
      <webElementGuid>bf3bafdb-edcd-4e8a-b487-88413258bce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Edit' and (text() = 'Onsite' or . = 'Onsite')]</value>
      <webElementGuid>877128d2-8126-4899-a8dc-15fd8e2767b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
