<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name_companyName</name>
   <tag></tag>
   <elementGuidId>b9a4c0a4-5469-4ce1-9cd8-8b6befd54f22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#companyName_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='companyName_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd7ce35d-881a-465a-893e-83f96f9cf45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ceeb0e7-5a49-4c7e-8f67-c329dec345f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>1c61ee10-825a-456a-8403-4585a8cd4d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>companyName_</value>
      <webElementGuid>554de56e-fc52-4775-8300-b1edfd52ba4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>companyName</value>
      <webElementGuid>896c1914-f845-4d6e-b33a-1a0caa6920ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;companyName_&quot;)</value>
      <webElementGuid>d5f1d5ad-6452-45a8-81bf-4784387a4fa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='companyName_']</value>
      <webElementGuid>abec0674-e709-45b2-af59-2113c99786f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalPlacement']/div/div/div[2]/form/div/input</value>
      <webElementGuid>3a48724c-8f46-476f-9a7d-257e80a4b232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/form/div/input</value>
      <webElementGuid>2e2b1993-93a5-4d49-87c0-4a34ae127c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'companyName_' and @name = 'companyName']</value>
      <webElementGuid>08e0abfe-babd-4a6a-a32b-8e407da0835b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
