<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Resource Application ServiceCSIRASResource Application Service</name>
   <tag></tag>
   <elementGuidId>40f62812-e15f-40b0-9bb6-c4ea00bff156</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deptId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='deptId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1f77814b-aac7-45ee-9cc2-476aea349fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deptId</value>
      <webElementGuid>7e00aff6-b071-4bd4-b7df-2a8781ee512d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectDept form-control</value>
      <webElementGuid>3c11f437-346a-4479-96ec-107d15b2489f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resource Application ServiceCSIRASResource Application Service</value>
      <webElementGuid>aa74abfd-5851-462d-9818-0d7066b30165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deptId&quot;)</value>
      <webElementGuid>93a37940-857f-4e01-bc75-4eb33286f5fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='deptId']</value>
      <webElementGuid>f06fbca3-8a94-4b46-8fae-2b125986b97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inputCompany']/p/select</value>
      <webElementGuid>93629e27-1650-4788-9bed-46c0b8595278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/select</value>
      <webElementGuid>515b5dc7-5aed-4dcf-9baf-81809a1bc1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'deptId' and (text() = 'Resource Application ServiceCSIRASResource Application Service' or . = 'Resource Application ServiceCSIRASResource Application Service')]</value>
      <webElementGuid>d2f01ba3-a165-4c75-8a0b-fabff41ff6e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
