<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Contract_end</name>
   <tag></tag>
   <elementGuidId>c4e58b6f-2755-4e3a-a0dc-3963716e674c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#end</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='end']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ce10069-cb72-443e-9d00-a9925899d053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>c6b798ec-94a2-47df-914a-fafb19c6081c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>f67bee2f-fa6a-4787-be52-f0eac26d09e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end</value>
      <webElementGuid>c16f39ac-1268-4a77-8d84-ae6439f331bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end</value>
      <webElementGuid>f4e88846-e8b5-46fb-81b4-1712df60ffe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;end&quot;)</value>
      <webElementGuid>edf90fd4-893a-43d0-84ab-70648c952b5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='end']</value>
      <webElementGuid>c300a633-5a52-47ff-b89b-a883385a4de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='createAccountForm']/div[3]/div[2]/input</value>
      <webElementGuid>569b396c-8bab-4524-999e-3d36da76e17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>8989f469-7488-4f87-a70b-594bc99316ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'end' and @name = 'end']</value>
      <webElementGuid>84312d72-c31d-4939-b7fa-5e1b064107c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
