<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_hiredStatus</name>
   <tag></tag>
   <elementGuidId>60698df5-a28c-422c-a5d1-4ba083c3f491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bootcamp</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f71d214-3c7b-44a2-a014-89065beee37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>910495c3-3adc-4f22-9c17-01696dcd4f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>4c0b4f64-b2a3-4ce9-81fa-7ba48a3a64fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bootcamp</value>
      <webElementGuid>7ecb153e-720f-4f73-b376-35a77ac7ddc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hiredStatus</value>
      <webElementGuid>0cb72784-060b-453a-bf12-19c23f795b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Bootcamp</value>
      <webElementGuid>65cd9cb5-3629-4871-b2a5-f57cafc4f6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bootcamp&quot;)</value>
      <webElementGuid>dfc7d0cf-ca9c-416b-ba81-79bf96ba7295</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bootcamp']</value>
      <webElementGuid>d2275a6f-8576-41b9-8eed-ab02bbd148fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='batch']/input</value>
      <webElementGuid>4b58bc94-5c6c-4f6f-bd6c-dea6aae31b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>3b556ec2-f43f-4cae-87c0-af2d9615795b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'bootcamp' and @name = 'hiredStatus']</value>
      <webElementGuid>2b4f1a87-949a-4b21-8b2c-7eeffe135123</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
