<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_hiredStatus_1</name>
   <tag></tag>
   <elementGuidId>0b5a79d8-5d62-45e2-8e1f-f92652223420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prohire</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prohire']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b249c3a-59f0-45da-85b5-9c0143f4a32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>293d0245-e640-4d39-a714-f9cd06969d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a1aa6024-d15d-4296-a80f-8211b8541c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prohire</value>
      <webElementGuid>863c3ce7-cec0-4d03-8a94-566b3cbefe28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hiredStatus</value>
      <webElementGuid>32d461d3-b2c2-4ae5-b1e3-2246dcffd598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Prohire</value>
      <webElementGuid>fcf7a163-a1b9-42b1-9b4f-0c9a56556142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prohire&quot;)</value>
      <webElementGuid>55627b65-dd58-4b17-ba97-fc1dc602b3c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prohire']</value>
      <webElementGuid>83541281-ee06-4487-9ef9-5b57a0cac91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='createAccountForm']/div/div[2]/div/input</value>
      <webElementGuid>461f40fe-0f77-401d-bd8b-392ba6d113a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/input</value>
      <webElementGuid>29fa8eaa-a51c-4ef1-bc93-191db803b34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'prohire' and @name = 'hiredStatus']</value>
      <webElementGuid>f9025942-41ec-408f-9d00-129d79c62fbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
