<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Join Date_join</name>
   <tag></tag>
   <elementGuidId>a7d49e4f-5c55-406c-9dd4-f9b6be1bd865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#join</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='join']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f33ce14-9967-443e-9569-45022d3f1296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>42946ca6-30ad-40f2-8e70-245333d15b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>bba5c9e9-bada-40f0-ab57-28f427091d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>join</value>
      <webElementGuid>726592ae-c69e-47ff-b8d6-66d56f6e8494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>join</value>
      <webElementGuid>3d3e83af-0be3-428b-a2e3-4e172d87a861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;join&quot;)</value>
      <webElementGuid>5c8c10bf-fb26-43ca-a823-0da6619c4b1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='join']</value>
      <webElementGuid>4f9d85b5-0509-4429-8a6c-f7b796d951d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='createAccountForm']/div[4]/div/input</value>
      <webElementGuid>8e7d79e9-cef8-414f-94e5-502b242b5f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>b69544f4-bdc4-4dfe-b3c9-6cb30ad1ef35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'join' and @name = 'join']</value>
      <webElementGuid>87bab987-80aa-489c-9d68-25ccb31b4406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
