<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Contract_start</name>
   <tag></tag>
   <elementGuidId>ad239743-1e7c-4fdc-a8f1-9bdfdec1d6e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#start</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='start']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70b3c0f4-797d-402c-8cb1-cf6470fbfa39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>496e66fb-1163-4832-a56d-25c8d3420784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>650d7bb1-f9d8-43f4-a6d6-504582c208ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>7f024a3c-b573-4ccc-a14a-85bfa026ba38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>start</value>
      <webElementGuid>17ca9d07-7d27-4535-8372-4504a9080a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start&quot;)</value>
      <webElementGuid>51216d2f-f754-4937-8eeb-ada02c2454fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='start']</value>
      <webElementGuid>cb26386f-b8ac-441d-bdf6-ce7f04ba0944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='createAccountForm']/div[3]/div/input</value>
      <webElementGuid>136d0301-c92b-4ead-bc6a-95d0aba682ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>6b95b085-6b45-4705-9b01-b277fc06b44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @id = 'start' and @name = 'start']</value>
      <webElementGuid>f89ddccd-7519-45e7-bd3f-43a6d8140647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
