<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Employee</name>
   <tag></tag>
   <elementGuidId>71d84a8b-6a77-44b5-93af-ef1d1f4a119b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick=&quot;return GetById('RAS04092023005')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bd95241-e385-4103-b4cc-5afecd4790ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge badge-pill badge-primary</value>
      <webElementGuid>bc378e74-9326-499e-896a-8a174e3159e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placement</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>0b8ca0c3-a995-4fa8-b258-f18e373267f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>823941b4-25e9-41c4-b28b-2903c1cffba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>animation</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>452d7289-0c09-43e6-9b9c-c7c8519ff1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>f4c07b6d-e377-4dc8-be45-2f0e5d6246a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return GetById('RAS04092023005')</value>
      <webElementGuid>47984c91-f64b-43b7-a9c7-4200bb106293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee</value>
      <webElementGuid>53cc9f5c-d690-46d9-a0c5-f2ab48646c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataTableAccounts&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[6]/button[@class=&quot;badge badge-pill badge-primary&quot;]</value>
      <webElementGuid>80336bed-eacf-46f2-8503-8b697d41ff88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick=&quot;return GetById('RAS04092023005')&quot;]</value>
      <webElementGuid>6c8fc1e9-de9f-4cfe-bb85-5b9a43ffca6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dataTableAccounts']/tbody/tr[3]/td[6]/button</value>
      <webElementGuid>7ec97e97-f254-468d-a4c1-10da5753fecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/button</value>
      <webElementGuid>e4619b14-74c3-44bd-b6db-d687aec9e618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Edit' and (text() = 'Employee' or . = 'Employee')]</value>
      <webElementGuid>3382d938-e556-4087-943e-2324bb201afd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
