<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Admin                            Employee</name>
   <tag></tag>
   <elementGuidId>b96b5bb9-4e03-4d3e-9392-b9880ccb444e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Role']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Role</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aa98f00e-5ddc-4df0-82fa-2f0b6a3a6886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Role</value>
      <webElementGuid>1fdd8a01-668b-48ef-b34f-a48a4fd89045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bd062c95-0df8-41d6-b722-2b893188b2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Admin
                            Employee
                        </value>
      <webElementGuid>e65dc9a8-0a9d-4f35-b8f1-b3361b6d0a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Role&quot;)</value>
      <webElementGuid>da949a00-a07c-4eba-a926-ee458e468db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Role']</value>
      <webElementGuid>cabf6e9d-c640-4328-b310-a480dd968afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Modal']/div/div/div[2]/form/div/select</value>
      <webElementGuid>07caf721-5039-46f1-b213-a053517f1e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>29e9a68e-4194-410b-bdf9-0a175c954ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Role' and (text() = '
                            Admin
                            Employee
                        ' or . = '
                            Admin
                            Employee
                        ')]</value>
      <webElementGuid>9b273bb1-31cc-4047-90a5-952ca4a12587</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
