<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Super_Admin</name>
   <tag></tag>
   <elementGuidId>b37707bc-fb0c-4996-9b73-a5a8bc6dfd6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='role']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#role</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2b5b3617-f487-490c-8c2c-37ddd308ff00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> d-none d-lg-inline</value>
      <webElementGuid>9ec96d91-2a5a-407e-be2b-68da208d2576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>role</value>
      <webElementGuid>8e15c02c-5c5e-4e7b-a356-a18d16828953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Super_Admin</value>
      <webElementGuid>2c4947dc-793e-4fd9-a3b5-5680319c4a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;role&quot;)</value>
      <webElementGuid>d7c1a942-5d7c-49cf-aad0-9dd17b0ca578</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='role']</value>
      <webElementGuid>8c931d9b-e2ae-4732-8cd2-f2b999b7b4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='userDropdown']/span[2]/span</value>
      <webElementGuid>bb6bb135-7465-4043-85f6-d46071bb446c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>4b45f125-bda2-4dd2-a141-f2956d162b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'role' and (text() = 'Super_Admin' or . = 'Super_Admin')]</value>
      <webElementGuid>6ba4a107-84a7-455a-aa39-7c7255de7094</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
