<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Department Name_NamaDept</name>
   <tag></tag>
   <elementGuidId>9e7cde9a-7cb8-4f43-be36-29ece279d070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NamaDept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NamaDept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca4e9a71-0e31-4772-849f-bebba6347659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8e2f08e-7a79-4611-9230-d89cbce30809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d09c9367-45c2-4242-b15b-4a607c7e2353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NamaDept</value>
      <webElementGuid>7f3fe728-46c2-47aa-889a-28806c293c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter department name</value>
      <webElementGuid>2013742c-e68d-458a-bce5-1d16b1e19fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NamaDept&quot;)</value>
      <webElementGuid>e139ad40-5f39-4acb-bd9f-37c4e4741cfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NamaDept']</value>
      <webElementGuid>b14e2549-8f59-4dde-9a1e-2c5fe1f339c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Modal']/div/div/div[2]/form/div[2]/input</value>
      <webElementGuid>0ff8ab85-4c63-4f5f-9b8b-d9f1d6488717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>4b67d242-92c3-471d-98a0-6a093fc5a9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'NamaDept' and @placeholder = 'Enter department name']</value>
      <webElementGuid>98da17ec-8e97-43c2-a9aa-fc9a1449a05d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
