<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_repeatPassword</name>
   <tag></tag>
   <elementGuidId>56fa09e6-e3b7-4ffb-863f-5a3632bd7e29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repeatPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#repeatPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70d8432a-dfee-4268-b774-1460136f2e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>88958ebf-6ed7-418e-86d0-c3fe9388a388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-user</value>
      <webElementGuid>f679724c-e618-47c3-9d57-d2831dc217f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repeatPassword</value>
      <webElementGuid>4da711dc-8c81-4fc2-8669-a80f41102baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeatPassword</value>
      <webElementGuid>9b6f47e9-e193-42cb-948a-c4ad098f451c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Repeate Password</value>
      <webElementGuid>b8916c26-d7e8-4d44-8d49-3b31ab72fb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeatPassword&quot;)</value>
      <webElementGuid>4fef6cd9-a5e8-4d7a-8732-1a622e9e0fc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repeatPassword']</value>
      <webElementGuid>802cc2e7-969a-437b-97f1-e43586e36367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='resetPassword']/div[3]/input</value>
      <webElementGuid>be9ecffa-5d6c-4db4-b14f-a62fa55a27d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>4e51e7df-69fe-4bae-a1b9-45ac794dad7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'repeatPassword' and @name = 'repeatPassword' and @placeholder = 'Repeate Password']</value>
      <webElementGuid>99b25db5-2f6e-4a60-9c7d-8ff7d3effbe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
