<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Super_Admin</name>
   <tag></tag>
   <elementGuidId>fa57a150-e7c7-4aca-aab0-755ce120ee4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='role']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#role</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fffbde77-ba13-4a52-8e8e-36609d87a828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> d-none d-lg-inline</value>
      <webElementGuid>41a251bb-8e54-4376-a0b7-44471247c108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>role</value>
      <webElementGuid>a99953f5-6204-49db-8930-5adf0af35aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Super_Admin</value>
      <webElementGuid>44573d2f-b6b4-4e6c-b809-7ca328e97f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;role&quot;)</value>
      <webElementGuid>ccda29b3-b051-4847-b5c7-a0bf9d404f97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='role']</value>
      <webElementGuid>6b94deb2-bb72-4aff-8d3b-e0d09c7f36c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='userDropdown']/span[2]/span</value>
      <webElementGuid>942d297f-3b3c-4a26-a209-4d323f2e2170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span</value>
      <webElementGuid>04318aa6-caf3-4359-884a-9ca40efcc607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'role' and (text() = 'Super_Admin' or . = 'Super_Admin')]</value>
      <webElementGuid>20202f88-2b07-42c9-8b07-15673f43c820</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
